name: Build

on: 
  push:
    tags:
      - "*"

  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true
        
jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main

      - name: Creating folders
        run: |
          New-Item -Path ReVanced_Builder -ItemType Directory -Force
          New-Item -Path Morphe_Builder -ItemType Directory -Force

      - name: YouTube ReVanced
        run: |
          # https://github.com/github/dmca/blob/master/2026/03/2026-03-12-morpheapp.md
          # .\Scripts\YouTube_ReVanced.ps1

      - name: YouTube Morphe
        run: |
          .\Scripts\YouTube_Morphe.ps1

      - name: ReVanced CLI
        run: |
          # ./Scripts\ReVanced_CLI.ps1

      - name: Morphe CLI
        run: |
          .\Scripts\Morphe_CLI.ps1

      - name: ReVanced Patches
        run: |
          # .\Scripts\ReVanced_Patches.ps1

      - name: Morphe Patches
        run: |
          .\Scripts\Morphe_Patches.ps1

      - name: ReVanced MicroG
        run: |
          # .\Scripts\MicroG_ReVanced.ps1

      - name: MicroG Morphe
        run: |
          .\Scripts\MicroG_Morphe.ps1

      - uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '26'

      - name: Building
        run: |
          # https://github.com/ReVanced/revanced-cli/tree/main/docs
          # https://github.com/MorpheApp/morphe-cli/tree/main/docs

          # Building Morphe
          java -jar "Morphe_Builder\morphe-cli.jar" `
          patch "Morphe_Builder\youtube.apk" `
          --patches "Morphe_Builder\morphe-patches.mpp" `
          --force `
          --purge `
          --out "Morphe_Builder\youtube_morphe.apk"

          # Building ReVanced
          # java -jar "ReVanced_Builder\revanced-cli.jar" `
          #patch "ReVanced_Builder\youtube.apk" `
          #--patches "ReVanced_Builder\revanced-patches.rvp" `
          #--force `
          #--purge `
          #--bypass-verification `
          #--out "ReVanced_Builder\youtube_revanced.apk"

      - name: Creating archive
        run: |
          $Parameters = @{
              Path             = "ReVanced_Builder\youtube_revanced.apk", "ReVanced_Builder\microg_revanced.apk", "ReVanced_Builder\microg_revanced_huawei.apk"
              DestinationPath  = "YouTube_ReVanced.zip"
              CompressionLevel = "Fastest"
              Force            = $true
          }
          #Compress-Archive @Parameters

          $Parameters = @{
              Path             = "Morphe_Builder\youtube_morphe.apk", "Morphe_Builder\microg_morphe.apk"
              DestinationPath  = "YouTube_Morphe.zip"
              CompressionLevel = "Fastest"
              Force            = $true
          }
          Compress-Archive @Parameters

      - name: Release Notes Template
        id: read_release
        run: |
          (Get-Content -Path ReleaseNotesTemplate.md -Encoding utf8 -Raw).Replace("ReVancedYTdot", "${{ env.ReVancedYTdot }}").
            Replace("CLIReVancedTag", "${{ env.CLIReVancedTag }}").
            Replace("ReVancedPatchesTag", "${{ env.ReVancedPatchesTag }}").
            Replace("MicroG_ReVanced", "${{ env.MicroG_ReVanced }}").
            Replace("MorpheYTdot", "${{ env.MorpheYTdot }}").
            Replace("CLIMorpheTag", "${{ env.CLIMorpheTag }}").
            Replace("MorphePatchesTag", "${{ env.MorphePatchesTag }}").
            Replace("MicroG_Morphe", "${{ env.MicroG_Morphe }}") | Set-Content -Path ReleaseNotesTemplate.md -Encoding utf8 -Force

          # https://trstringer.com/github-actions-multiline-strings/
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ReleaseBody=ReleaseNotesTemplate.md"

          $ReleaseName = Get-Date -f "yyyy.MM.dd"
          echo "RELEASE_NAME=$ReleaseName" >> $env:GITHUB_ENV

      - name: Uploading
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ env.RELEASE_NAME }}
          token: ${{ github.token }}
          prerelease: false
          body_path: ${{ steps.read_release.outputs.ReleaseBody }}
          files: |
            YouTube_ReVanced.zip
            YouTube_Morphe.zip

